baseURL = 'https://www.dleibovych.com/'
languageCode = 'en-us'
title = 'David Leibovych'
theme = "anatole"

[params]
title = 'David Leibovych'
author = "David Leibovych"
description = """
My name is David
I love programming and D&D
"""
profilePicture = "images/small_avatar.jpg"
doNotLoadAnimations = true
favicon = "favicons/"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ariedov/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/ariedov/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "linkedin"
url = "https://www.linkedin.com/in/david-leibovych-11587428/"
